### ISSUE TITLE
Sample training dataset

### ISSUE THREAD

**Issue by deepseek** [ocr-d-modul-2-segmentierung/page-segmentation#1]
Thank you for your hard work

It would be great if you upload a sample training dataset & json file, just so that i can understand the structure of the dataset required for training. even if it's just a few images.

**Comment by crater2150** [comment]
Hi, you can find some publicly available data in the [OCR-D repositories](https://ocr-d-repo.scc.kit.edu/api/v1/metastore/bagit). These contain color images and PAGEXML. You'll have to generate binarized images and then follow the examples for [dataset generation](https://github.com/ocr-d-modul-2-segmentierung/page-segmentation/blob/master/examples/dataset-creation-example.sh) to generate the json files.

The example assumes subfolders of `binary`, `jpg` and `page` for binarization, color image and xml. In the OCR-D zip files, the folder for color image is `OCR-D-IMG`, and you should use the PAGEXML from `OCR-D-GT-SEG-BLOCK`, so change the paths in the example accordingly (as I said you'll have to generate binaries yourself, put them in a separate folder).
